name: CI

on: 
  workflow_dispatch:
    inputs:
      qosFile:
        description: "qos file to deploy"
        required: true
        default: "true"
        type: choice
        options:
          - qos-ant-uat.json
          - qos-staging-us.json
      environment:
        description: ""
        required: true
        type: choice
        options:
          - dev
          - prod
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run a script
      run: echo "Hello from GitHub Actions!"
